version: '3.1'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: games
    volumes:
      - ./datasets:/tmp/datasets/
      - ./datasets/createdb.sql:/docker-entrypoint-initdb.d/createdb.sql

  jupyter:
    image: jupyter/scipy-notebook
    volumes:
      - ./notebook.ipynb:/home/jovyan/notebook.ipynb
    ports:
      - 8888:8888
    depends_on:
      - db